name: build kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    container:
      image: ubuntu:18.04

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            build-essential bc bison flex cpio python3 libssl-dev \
            wget zip git gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi gcc-arm-none-eabi \
            libelf-dev dwarves ca-certificates

      - name: Build Kernel
        run: |
          # Нейтрализуем BUILD_BUG
          sed -i 's/#define BUILD_BUG() BUILD_BUG_ON_MSG(1, "BUILD_BUG failed")/#define BUILD_BUG() do { } while (0)/g' include/linux/build_bug.h
          
          # Настройка окружения
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          
          make clean && make mrproper
          make akx_extreme_defconfig

          # Отключаем FORTIFY_SOURCE
          sed -i 's/CONFIG_FORTIFY_SOURCE=y/CONFIG_FORTIFY_SOURCE=n/g' .config
          
          # СОБИРАЕМ
          make -j$(nproc) \
            KBUILD_CFLAGS='-D__compiletime_error= -w -Wno-error -Wno-attribute-warning -fno-strict-aliasing -fno-stack-protector -std=gnu89' \
            HOSTCFLAGS='-w -Wno-error'

      - name: Package with AnyKernel3
        run: |
          cp arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cd AnyKernel3
          zip -r9 ../KuroNeko-Extreme-$(date +%d%m%y).zip *

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: KuroNeko-Extreme-Kernel
          path: KuroNeko-Extreme-*.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "KuroNeko-v${{ github.run_id }}"
          name: "KuroNeko Extreme Kernel Build (Ubuntu 18.04)"
          body: |
            ### 🥟 Автоматическая сборка ядра KuroNeko Extreme
            * **Особенности:** Вшит KernelSU-Next (Legacy) без gki.
            * **Окружение:** Ubuntu 18.04 (для совместимости с PowerVR).
            * **Пакет:** Flashable via AnyKernel3.
          files: KuroNeko-Extreme-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
