name: Build KuroNeko Extreme Kernel

on:
  workflow_dispatch: # Кнопка ручного запуска в интерфейсе GitHub

jobs:
  build:
    runs-on: ubuntu-22.04 # Стабильное облачное окружение
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Compilers and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential libncurses5-dev libssl-dev xz-utils bison flex ccache \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            libelf-dev \
            pkg-config
      - name: Build Kernel Core
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          make akx_extreme_defconfig
          make olddefconfig
          make -j$(nproc)

      - name: Prepare Artifact for Release
        run: |
          # Переименовываем бинарник в красивое имя, чтобы везде всё было четко
          mkdir -p release_output
          cp arch/arm64/boot/Image.gz-dtb release_output/KuroNeko-Extreme.gz-dtb

      - name: Upload to Actions Artifacts (Страховка)
        uses: actions/upload-artifact@v4
        with:
          name: KuroNeko-Extreme-Artifact
          path: release_output/KuroNeko-Extreme-PELMENI.gz-dtb

      - name: Generate Release Tag
        id: tag
        run: echo "release_tag=KuroNeko-v$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Upload and Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: "KuroNeko Extreme Kernel Build"
          body: |
            ### 🥟 Автоматическая сборка ядра KuroNeko Extreme
            * **Особенности:** Вшит KernelSU-Next (Legacy) без gki.
            * **Компилятор:** `GCC 10`.
          files: release_output/KuroNeko-Extreme.gz-dtb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
