name: Ubuntu slim Host machine builder

on:
  workflow_dispatch:

jobs:
  overkill:
    runs-on: ubuntu-22.04-arm
    container: ubuntu:20.04
    timeout-minutes: 360

    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      
      - name: Setup environment and GCC toolchain
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y tzdata
          apt-get install -y sudo curl bc bison build-essential ccache flex libssl-dev libelf-dev python3 git wget \
                             gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabi
                                  
      - name: change password from root
        env:
          PASSWORD: ${{ secrets.ADMIN_PASS }}
        run: |
          # Убедимся, что SSH-сервер установлен
          apt-get update && apt-get install -y openssh-server
          
          # Разрешаем вход под root и авторизацию по паролю/ключам
          sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sed -i 's/#PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

          # Создаем необходимую для работы sshd папку, если её нет
          mkdir -p /var/run/sshd

          # Запускаем SSH-сервер принудительно
          service ssh start || /usr/sbin/sshd
          
          # Задаем пароль для нативного юзера 'runner'
          echo "root:$PASSWORD" | chpasswd

      # 1. Скачиваем репозиторий с твоим docker-compose.yml
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Коннектимся к Tailscale по твоему ключу tskey-...
      - name: Connect to Tailscale Network
        run: |
          # Add Tailscale's GPG key
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
          # Add the tailscale repository
          curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/focal.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
          # Install Tailscale
          sudo apt-get update && sudo apt-get install tailscale -y
          sudo tailscaled --tun=userspace-networking &
          # Start Tailscale!
          sudo tailscale up
          
      - name: вечный затык
        run: |
          # Железобетонный вечный затык
          tail -f /dev/null
