name: Ubuntu slim Host machine builder

on:
  workflow_dispatch:

jobs:
  overkill:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
#      - name: Cleanup
#        uses: rokibhasansagar/slimhub_actions@main
      
      - name: Setup environment and GCC toolchain
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt-get update
          apt-get install -y tzdata
          apt-get install -y sudo curl bc bison build-essential ccache flex libssl-dev libelf-dev python3 git wget \
                             gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabi
                                  
      - name: change password from root
        env:
          PASSWORD: ${{ secrets.ADMIN_PASS }}
        run: |
          # Задаем пароль для нативного юзера 'runner'
          echo "runner:$PASSWORD" | chpasswd

      # 1. Скачиваем репозиторий с твоим docker-compose.yml
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Коннектимся к Tailscale по твоему ключу tskey-...
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAIL_KEY }}
          hostname: runner-builder
          use-cache: 'true'
          args: '--advertise-exit-node'
    
          
      - name: вечный затык
        run: |
          # Железобетонный вечный затык
          tail -f /dev/null
